export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL!;

export const API_ROUTES = {
  shipments: "/shipments",
  shipmentById: (id: string) => `/shipments/${id}`,
  shipmentByReference: (reference: string) => `/shipments/reference/${reference}`,
  tracking: (trackingNumber: string) => `/tracking/${trackingNumber}`,
  trucks: "/trucks",
  truckById: (id: string) => `/trucks/${id}`,
  routeById: (id: string) => `/routes/${id}`,
  docks: "/docks",
  // Registered ahead of `/docks/:id` on the backend so `schedule` is never
  // matched as a dock id — kept as its own constant for the same reason.
  dockSchedule: "/docks/schedule",
  dockById: (id: string) => `/docks/${id}`,
  dockStatus: (id: string) => `/docks/${id}/status`,
  dockRelease: (id: string) => `/docks/${id}/release`,
  dockRecommendations: (truckId: string) => `/trucks/${truckId}/dock-recommendations`,
  dockAssignment: (truckId: string) => `/trucks/${truckId}/dock-assignment`,
  dockAssignments: "/dock-assignments",
  alerts: "/alerts",
  yardOverview: "/yard/overview",
  yardDockingQueue: "/yard/docking-queue",
  yardAllocationSummary: "/yard/allocation-summary",
  simulationStart: "/simulation/start",
  simulationStop: "/simulation/stop",
  simulationReset: "/simulation/reset",
  simulationStatus: "/simulation/status",
  simulationState: "/simulation/state",
  simulationTruck: (truckId: string) => `/simulation/trucks/${truckId}`,
  simulationTruckDelay: (truckId: string) => `/simulation/trucks/${truckId}/delay`,
  simulationTruckClearDelay: (truckId: string) => `/simulation/trucks/${truckId}/clear-delay`,
  wmsEvents: "/wms/events",
  wmsSimulate: "/wms/simulate",
} as const;
